# Generated by Django 5.0.6 on 2024-08-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('post', '0002_post_image_alter_post_author_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
